CREATE OR REPLACE PROCEDURE INSERTTASK
IS

TID TASK.TASKID%TYPE;
D TASK.DES%TYPE;
T TASK.TIME%TYPE;
K TASK.KEENID%TYPE;
S TASK.ISSOLVE%TYPE;

I NUMBER(2);


BEGIN
 
   FOR I IN 1..25 LOOP
   
   TID:=CONCAT('T000000',I);  
    S:='F';
    D:=CONCAT('TASK DESCRIPTION ',I);
    T:=SYSDATE+I;
    /*K:= SELECT *  FROM (SELECT KEENID FROM KEEN ORDER BY DBMS_RANDOM.VALUE)WHERE ROWNUM=1;   */
    K:=CONCAT('K000000',I);
  
    INSERT INTO TASK VALUES(TID,D,T,K,S);
   END LOOP;
END INSERTTASK;